export const SET_LOADING:string = 'SET_LOADING';
export const SET_POSTS:string = 'SET_POSTS';
export const SET_CATEGORY:string = 'SET_CATEGORY';
export const SET_PARAM_ALERT:string = 'SET_PARAM_ALERT';
export const GET_SEARCH:string = 'GET_SEARCH';
export const SET_SEARCH_INPUT:string = 'SET_SEARCH_INPUT';
export const SET_SEARCH_CATEGORY:string = 'SET_SEARCH_CATEGORY';
export const SET_SEARCH_PRICERANGE:string = 'SET_SEARCH_PRICERANGE';


// loginreducer

export const SET_LOGIN_PASSWORD = 'SET_LOGIN_PASSWORD';
export const SET_LOGIN_USEROREMAIL = 'SET_LOGIN_USEROREMAIL';
export const SET_LOGIN_MESSAGE = 'SET_LOGIN_MESSAGE';


// userreducer


export const SET_USER_LOGGED_IN = 'SET_USER_LOGGED_IN';
export const SET_USER_LOGGED_IN_USERNAME = 'SET_USER_LOGGED_IN_USERNAME';
export const SET_USER_ATTEMPTED_AUTH = 'SET_USER_ATTEMPTED_AUTH';


// register reducer


export const SET_REGISTER_EMAIL = 'SET_REGISTER_EMAIL';
export const SET_REGISTER_PASSWORD = 'SET_REGISTER_PASSWORD';
export const SET_REGISTER_LOADING = 'SET_REGISTER_LOADING';
export const SET_REGISTER_NAME = 'SET_REGISTER_NAME';
export const SET_REGISTER_USERNAME = 'SET_REGISTER_USERNAME';
export const SET_REGISTER_RESPONSE_MESSAGE = 'SET_REGISTER_RESPONSE_MESSAGE';


// PROFILEREDUCER

export const SET_PROFILE_USERNAME = 'SET_PROFILE_USERNAME';
export const SET_PROFILE_BIO = 'SET_PROFILE_BIO';
export const SET_PROFILE_NAMEHEAD = 'SET_PROFILE_NAMEHEAD';

export const SET_PROFILE_LOADING = 'SET_PROFILE_LOADING';
export const SET_PROFILE_DATA = 'SET_PROFILE_DATA';



// create post reducer


export const SET_CREATEPOST_LOADING =  'SET_CREATEPOST_LOADING';
export const SET_CREATEPOST_TITLE =  'SET_CREATEPOST_TITLE';
export const SET_CREATEPOST_CATEGORY =  'SET_CREATEPOST_CATEGORY';
export const SET_CREATEPOST_URL =  'SET_CREATEPOST_URL';
export const SET_CREATEPOST_PRICE =  'SET_CREATEPOST_PRICE';
export const SET_CREATEPOST_MESSAGE =  'SET_CREATEPOST_MESSAGE';


//

export const SET_USER_LOGGED_IN_PFP = 'SET_USER_LOGGED_IN_PFP'